List=[]

ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
ans= input('pick any number')
List.apppend(ans)
print(List)
